import os

OKANBAN_PORT = int(os.getenv('OKANBAN_PORT', 50890))

OKANBAN_CONSOLE_LEVEL = os.getenv('OKANBAN_CONSOLE_LEVEL', 'DEBUG')
OKANBAN_LOGFILE_LEVEL = os.getenv('OKANBAN_LOGFILE_LEVEL', 'INFO')

OKANBAN_MONGODB_HOST = os.getenv('OKANBAN_MONGODB_HOST', '192.168.0.20')
OKANBAN_MONGODB_PORT = int(os.getenv('OKANBAN_MONGODB_PORT', 27017))

OKANBAN_NICELABEL_URL = os.getenv('OKANBAN_NICELABEL_URL', 'http://192.168.0.16:56426')

OKANBAN_API_USERNAME = os.getenv('OKANBAN_API_USERNAME', 'olfa')
OKANBAN_API_PASSWORD = os.getenv('OKANBAN_API_PASSWORD', 'Trone08')

OKANBAN_ETIQUETTE = os.getenv('OKANBAN_ETIQUETTE', 'ET_PER_API')


